services:
  - type: web
    name: mern-ecommercee-frontend
    env: static
    buildCommand: cd client && yarn install && yarn build
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html